import { PublicKey } from "@solana/web3.js";

/**
 * Canonical program IDs for SUR Protocol on Solana.
 *
 * These IDs are generated by `cargo-build-sbf` and committed in
 * `Anchor.toml` + each program's `lib.rs` `declare_id!`. They are
 * canonical for **devnet/testnet/dev**. Mainnet rotation happens at v1.0.
 */
export const SUR_PROGRAM_IDS = {
  a2a_darkpool: new PublicKey("BVrt7REAZoCZBEY987fUPEjn2EvnXyaFzpMPVXb81rnq"),
  perp_vault: new PublicKey("FpbuRBF3RiAkpD3k8XccnoYH99W5g9R59aRd3jRZTBfU"),
  oracle_router: new PublicKey("CC5Xc5DTyLSfcw3MiXbyJQyRA21mh3Shup6bgMH8WGSS"),
  perp_engine: new PublicKey("Cwpbe4mwgFdnhwhoRBGBzUerQa52cJMqXWjG3wGvYFW8"),
  sur_timelock: new PublicKey("9FeQoWChgaRqvKJGqjTmVvpF7jQ4Ph7zgSsrkA4NnwAF"),
} as const;
