import { PublicKey } from "@solana/web3.js";

/**
 * Canonical program IDs for SUR Protocol on Solana.
 *
 * These IDs are generated by `cargo-build-sbf` and committed in
 * `Anchor.toml` + each program's `lib.rs` `declare_id!`. They are
 * canonical for **devnet/testnet/dev**. Mainnet rotation happens at v1.0.
 */
export const SUR_PROGRAM_IDS = {
  a2a_darkpool: new PublicKey("DAK23pRLEr7E4JaSGRpeo8TEV5fjz6edqS5ZbvnJ5sAR"),
  perp_vault: new PublicKey("2iidk56xin9riWJDdfR9BpFU3sLH4oZbPwQrK64Y3xf1"),
  oracle_router: new PublicKey("8yLenSHEkdkbsCiQLmiQrZg7Kdb3ZBb1MKTFmJsA37zk"),
  perp_engine: new PublicKey("28pVZVVY2MyxmukdDTcz85zD88TsfDBhqovgU6ARW6SX"),
  sur_timelock: new PublicKey("HBAd2wkpL3zuuvHG5VmPWvVz66U2u9G4SGH4XKavVFga"),
  // Phase 2 — second half
  liquidator: new PublicKey("38zdeFX8qeXep53DYRM8ssBEQwu9Ztja6HBFGxrhpDUy"),
  insurance_fund: new PublicKey("33WMHTYxURf1t65CoHuPGSD1ZPcRQ3KQi22Bdo92nxpA"),
  auto_deleveraging: new PublicKey("J6qRhEyU45T17LhiPyoKGrHUvcMEKgH6iy5kxNUvcEHn"),
  collateral_manager: new PublicKey("94Pu8AJXwwpoexNfs6oQ4SEq6x3sRhyLEA5AvNPuLGc1"),
  trading_vault: new PublicKey("8eXKqX7ZwVrJUH78urAsVoBiQQ1tgifmfBwhdiMepT3K"),
  order_settlement: new PublicKey("6YiGUHjvSPKzS3ypDvodsbqH4ibiV3xTfq5FJeW5kfmo"),
} as const;
