[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
a2a_darkpool = "DAK23pRLEr7E4JaSGRpeo8TEV5fjz6edqS5ZbvnJ5sAR"
auto_deleveraging = "J6qRhEyU45T17LhiPyoKGrHUvcMEKgH6iy5kxNUvcEHn"
collateral_manager = "94Pu8AJXwwpoexNfs6oQ4SEq6x3sRhyLEA5AvNPuLGc1"
insurance_fund = "33WMHTYxURf1t65CoHuPGSD1ZPcRQ3KQi22Bdo92nxpA"
liquidator = "38zdeFX8qeXep53DYRM8ssBEQwu9Ztja6HBFGxrhpDUy"
oracle_router = "8yLenSHEkdkbsCiQLmiQrZg7Kdb3ZBb1MKTFmJsA37zk"
order_settlement = "6YiGUHjvSPKzS3ypDvodsbqH4ibiV3xTfq5FJeW5kfmo"
perp_engine = "28pVZVVY2MyxmukdDTcz85zD88TsfDBhqovgU6ARW6SX"
perp_vault = "2iidk56xin9riWJDdfR9BpFU3sLH4oZbPwQrK64Y3xf1"
sur_timelock = "HBAd2wkpL3zuuvHG5VmPWvVz66U2u9G4SGH4XKavVFga"
trading_vault = "8eXKqX7ZwVrJUH78urAsVoBiQQ1tgifmfBwhdiMepT3K"

[programs.localnet]
a2a_darkpool = "BVrt7REAZoCZBEY987fUPEjn2EvnXyaFzpMPVXb81rnq"
auto_deleveraging = "F12KjhGRyiEbM629MHookPFar7xsbfbfafoZjuBmCTDz"
collateral_manager = "2LavJpzUzHWs2cJTAp2BEvvS2Kxrr9gfaWgSVH4s3juh"
insurance_fund = "A9TY4wcr6Buzrac5XLC5aQvz4wWyYjQSogsVBvS3eKPp"
liquidator = "9APXqgHS7aNtYsjDE1SJ6PiboJPSyv2QhG9SmLaCzg2R"
oracle_router = "CC5Xc5DTyLSfcw3MiXbyJQyRA21mh3Shup6bgMH8WGSS"
order_settlement = "2q4HtPAjUMFPDfipazQhb52sRun3x9TdpwRHysWBg6Vf"
perp_engine = "Cwpbe4mwgFdnhwhoRBGBzUerQa52cJMqXWjG3wGvYFW8"
perp_vault = "FpbuRBF3RiAkpD3k8XccnoYH99W5g9R59aRd3jRZTBfU"
sur_timelock = "9FeQoWChgaRqvKJGqjTmVvpF7jQ4Ph7zgSsrkA4NnwAF"
trading_vault = "JE4JwZ3b7eYoBsTempCUbkBiFAgYrTsisn2uMssWGvCy"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = ["programs/a2a_darkpool", "programs/perp_vault", "programs/oracle_router", "programs/perp_engine", "programs/sur_timelock", "programs/liquidator", "programs/insurance_fund", "programs/auto_deleveraging", "programs/collateral_manager", "programs/trading_vault", "programs/order_settlement"]

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 'tests/**/*.ts'"
