//! A2A Dark Pool — agent-to-agent OTC perp matching with persistent reputation.
//!
//! Solana port of SUR Protocol's A2ADarkPool.sol, byte-by-byte mapped to
//! Anchor + PDA model. See docs/MAPPING.md for the side-by-side equivalence
//! and docs/ARCHITECTURE.md for the PDA layout + CPI plan.
//!
//! Source contract: github.com/asastuai/sur-protocol/blob/master/contracts/src/A2ADarkPool.sol

use anchor_lang::prelude::*;

pub mod errors;
pub mod events;
pub mod instructions;
pub mod state;

use instructions::*;

// Generated by cargo-build-sbf on first build (target/deploy/a2a_darkpool-keypair.json).
// Rotate before mainnet deploy.
declare_id!("3jPooLaiWoq5DA4SeXMfP4MT4hrp6X1zrASD9hcYqKke");

#[program]
pub mod a2a_darkpool {
    use super::*;

    // ====================== INIT + ADMIN ======================

    pub fn initialize(
        ctx: Context<Initialize>,
        fee_bps: u64,
        large_trade_threshold: u64,
        large_trade_min_reputation: u64,
        min_intent_duration: i64,
        max_intent_duration: i64,
        response_cooldown: i64,
    ) -> Result<()> {
        instructions::admin::initialize(
            ctx,
            fee_bps,
            large_trade_threshold,
            large_trade_min_reputation,
            min_intent_duration,
            max_intent_duration,
            response_cooldown,
        )
    }

    pub fn transfer_ownership(ctx: Context<AdminUpdate>, new_owner: Pubkey) -> Result<()> {
        instructions::admin::transfer_ownership(ctx, new_owner)
    }

    pub fn accept_ownership(ctx: Context<AcceptOwnership>) -> Result<()> {
        instructions::admin::accept_ownership(ctx)
    }

    pub fn set_fee_bps(ctx: Context<AdminUpdate>, new_fee_bps: u64) -> Result<()> {
        instructions::admin::set_fee_bps(ctx, new_fee_bps)
    }

    pub fn set_fee_recipient(ctx: Context<AdminUpdate>, new_recipient: Pubkey) -> Result<()> {
        instructions::admin::set_fee_recipient(ctx, new_recipient)
    }

    pub fn set_large_trade_threshold(ctx: Context<AdminUpdate>, threshold: u64) -> Result<()> {
        instructions::admin::set_large_trade_threshold(ctx, threshold)
    }

    pub fn set_large_trade_min_reputation(ctx: Context<AdminUpdate>, min_rep: u64) -> Result<()> {
        instructions::admin::set_large_trade_min_reputation(ctx, min_rep)
    }

    pub fn pause(ctx: Context<AdminUpdate>) -> Result<()> {
        instructions::admin::pause(ctx)
    }

    pub fn unpause(ctx: Context<AdminUpdate>) -> Result<()> {
        instructions::admin::unpause(ctx)
    }

    // ====================== INTENT FLOW ======================

    pub fn post_intent(
        ctx: Context<PostIntent>,
        market_id: [u8; 32],
        is_buy: bool,
        size: u64,
        min_price: u64,
        max_price: u64,
        duration: i64,
    ) -> Result<()> {
        instructions::post_intent::handler(
            ctx, market_id, is_buy, size, min_price, max_price, duration,
        )
    }

    pub fn cancel_intent(ctx: Context<CancelIntent>) -> Result<()> {
        instructions::cancel_intent::handler(ctx)
    }

    // ====================== RESPONSE FLOW ======================

    pub fn post_response(ctx: Context<PostResponse>, price: u64, duration: i64) -> Result<()> {
        instructions::post_response::handler(ctx, price, duration)
    }

    pub fn cancel_response(ctx: Context<CancelResponse>) -> Result<()> {
        instructions::cancel_response::handler(ctx)
    }

    // ====================== SETTLEMENT ======================

    pub fn accept_and_settle(ctx: Context<AcceptAndSettle>) -> Result<()> {
        instructions::accept_and_settle::handler(ctx)
    }
}
